# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "tester-kali" do |tester|
    tester.vm.box = "kali"
    tester.vm.guest = :debian
    tester.vm.provider 'virtualbox' do |v|
      v.customize ['modifyvm', :id, '--name', 'tester-kali']
    end

    tester.vm.network :private_network, ip: '10.13.37.2'
  end

  config.vm.define "target-metasploitable2" do |target|
    target.vm.box = "metasploitable2"

    target.vm.provider 'virtualbox' do |v|
      v.customize ['modifyvm', :id, '--name', 'target-metasploitable2']
    end

    target.vm.network :private_network, ip: '10.13.37.10'
  end
end
