# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "tester-kali" do |tester|
    tester.vm.box = "kali"
    tester.vm.guest = :debian
    tester.vm.provider 'virtualbox' do |v|
      v.customize ['modifyvm', :id, '--name', 'tester-kali']
    end

    tester.vm.network :private_network, ip: '10.13.37.2',
                      virtualbox__intnet: "virtual-security-testing-network"
  end

  config.vm.define "target-metasploitable2" do |target|
    target.vm.box = "metasploitable2"

    target.vm.provider 'virtualbox' do |v|
      v.customize ['modifyvm', :id, '--name', 'target-metasploitable2']
    end

    target.vm.network :private_network, ip: '10.13.37.10',
                      virtualbox__intnet: "virtual-security-testing-network"
  end

  config.vm.define "target-debian-lenny" do |target|
    target.vm.box = "debian-lenny"

    target.vm.provider 'virtualbox' do |v|
      v.customize ['modifyvm', :id, '--name', 'target-debian-lenny']
    end

    target.vm.network :private_network, ip: '10.13.37.20',
                      virtualbox__intnet: "virtual-security-testing-network"
  end

  config.vm.define "target-dvna" do |target|
    target.vm.box = "dvna"

    target.vm.provider 'virtualbox' do |v|
      v.customize ['modifyvm', :id, '--name', 'target-dvna']
    end

    target.vm.network :private_network, ip: '10.13.37.30',
                      virtualbox__intnet: "virtual-security-testing-network"

    target.vm.provision "shell", run: "always" do |s|
      s.privileged = false
      s.inline = "source .nvm/nvm.sh && cd DVNA && nohup node dvna.js > dvna.log &"
    end
  end
end
